//! Print intermediate representation (IR) — the one representation shared by
//! the real ESC/POS output and the on-screen print preview.
//!
//! A single template run produces BOTH artefacts:
//!   * `PrintDoc::escpos` — the exact bytes written to the Xprinter,
//!   * `PrintDoc::ops`    — the same drawing operations, in the same order.
//!
//! The preview is therefore generated by the renderer that produces the
//! printer bytes: it cannot drift from the real output. Semantic item and
//! financial operations describe source fields for the screen while their
//! physical text lines are emitted unchanged to ESC/POS; no second (HTML)
//! receipt implementation exists anywhere in the project.

use super::escpos::Align;
use serde::Serialize;

/// Paper width in millimetres — 80mm thermal roll (Xprinter).
pub const PAPER_MM: f64 = 80.0;

/// One drawing operation, mirroring exactly what `EscPos` emitted.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum PreviewOp {
    /// Monochrome raster (brand logo): 1 bit per dot, MSB first, packed rows —
    /// the same payload sent as ESC/POS `GS v 0`.
    Logo {
        width_dots: usize,
        height_dots: usize,
        bits_hex: String,
        align: Align,
    },
    /// A text line exactly as the printer receives it: visual order applied
    /// (RTL runs reordered) and codepage-mapped, with the active attributes.
    Text {
        text: String,
        align: Align,
        bold: bool,
        width: u8,
        height: u8,
    },
    /// A semantic item row produced by the same template data as its printer
    /// lines. Values are already formatted by the authoritative template; the
    /// screen renderer only lays them out.
    Item {
        name: String,
        quantity: String,
        unit_price: String,
        line_total: String,
        align: Align,
    },
    /// A semantic financial row. `total` is the document's payable amount.
    Financial {
        label: String,
        value: String,
        total: bool,
        align: Align,
    },
    /// A semantic metadata row of the invoice/receipt identity block (date,
    /// time, invoice number, customer, table, car, …).
    ///
    /// It exists so the screen can lay the identity block out across the FULL
    /// printable width as a real two-column row. Printing it as padded text
    /// alone forced the screen to right-align a padded string, which is what
    /// made the metadata look narrower than the item table below it. The
    /// physical line this op emits is byte-identical to [`EscPos::kv_line`].
    Meta {
        label: String,
        value: String,
        /// Print emphasis: the document's own moment (date/time) is the one
        /// metadata a reader always looks for, so it is set apart from the
        /// low-priority rows around it — by weight, never by bulk.
        emphasis: bool,
        align: Align,
    },
    /// `ESC d n` — n blank lines.
    Feed { lines: u8 },
    /// `GS V 0` — full paper cut.
    Cut,
}

/// Everything one template produced: printer bytes + preview operations.
#[derive(Debug, Clone)]
pub struct PrintDoc {
    pub escpos: Vec<u8>,
    pub ops: Vec<PreviewOp>,
}

/// Serializable payload returned by the read-only `preview_*` commands.
#[derive(Debug, Clone, Serialize)]
pub struct PrintPreview {
    pub doc_type: String,
    pub paper_mm: f64,
    pub width_chars: usize,
    pub ops: Vec<PreviewOp>,
}

impl PrintPreview {
    pub fn new(doc_type: impl Into<String>, doc: &PrintDoc) -> Self {
        Self {
            doc_type: doc_type.into(),
            paper_mm: PAPER_MM,
            width_chars: super::templates::WIDTH,
            ops: doc.ops.clone(),
        }
    }
}

/// Lowercase hex — keeps the raster payload JSON-safe without adding a base64
/// dependency to the build.
pub(crate) fn to_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0F) as usize] as char);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_round_trips_a_raster_payload() {
        assert_eq!(to_hex(&[0x00, 0x0F, 0xA5, 0xFF]), "000fa5ff");
    }
}
