/**
 * Single icon system for the whole app — lucide-react (already a dependency).
 * Everything imports from here so there is exactly one icon library and one
 * sizing convention. Icons inherit `currentColor`, so they work in light and
 * dark themes and are RTL-neutral.
 */

export {
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  Ban,
  Car,
  CarFront,
  Pin,
  PinOff,
  Maximize2,
  BarChart3,
  Boxes,
  CalendarClock,
  CalendarDays,
  Check,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Calculator,
  ClipboardList,
  Clock,
  Coffee,
  Coins,
  Copy,
  Delete,
  Divide,
  Equal,
  Eraser,
  History,
  DoorClosed,
  DoorOpen,
  Download,
  Droplets,
  Eye,
  Gauge,
  Inbox,
  EyeOff,
  FileDown,
  FilterX,
  FileUp,
  HandCoins,
  Layers,
  Loader2,
  Lock,
  LogOut,
  Minus,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Package,
  Pencil,
  Percent,
  Plus,
  Power,
  Printer,
  QrCode,
  Tag,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Save,
  ScrollText,
  Search,
  Settings,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Moon,
  Store,
  Ticket,
  TrendingDown,
  TrendingUp,
  Trash2,
  Upload,
  User,
  UserPlus,
  UserRound,
  UserX,
  Users,
  Wallet,
  X,
  Bell,
  CircleAlert,
  CircleSlash,
  TriangleAlert,
} from 'lucide-react'

export type { LucideIcon } from 'lucide-react'

/** Standard icon sizes — use these instead of ad-hoc pixel values. */
// Barrel of icon re-exports plus the size table; splitting it would only
// fragment the icon API.
// oxlint-disable-next-line react/only-export-components
export const iconSize = { sm: 14, md: 16, lg: 20 } as const
